# Generated by Django 5.2.5 on 2025-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='insignias',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.insignia'),
        ),
    ]
