# Generated by Django 5.2.5 on 2025-09-03 16:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_insignias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Entero'), ('float', 'Número Decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON')], default='string', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('modificable_por_usuario', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['categoria', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('export', 'Exportación'), ('import', 'Importación'), ('error', 'Error'), ('system', 'Acción del Sistema')], max_length=20)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('achievement', 'Logro'), ('system', 'Sistema')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('url_accion', models.URLField(blank=True, help_text='URL para redireccionar al hacer clic')),
                ('texto_accion', models.CharField(blank=True, help_text='Texto del botón de acción', max_length=50)),
                ('prioridad', models.PositiveIntegerField(default=1, help_text='1=Baja, 5=Crítica')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Error', 'verbose_name_plural': 'Errores'},
        ),
        migrations.AlterModelOptions(
            name='insignia',
            options={'ordering': ['tipo', 'nivel_requerido', 'nombre'], 'verbose_name': 'Insignia', 'verbose_name_plural': 'Insignias'},
        ),
        migrations.AlterModelOptions(
            name='metrica',
            options={'ordering': ['-fecha'], 'verbose_name': 'Métrica', 'verbose_name_plural': 'Métricas'},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='error',
            name='corregido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='error',
            name='corregido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_corregidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='error',
            name='fecha_correccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='frecuencia_patron',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='error',
            name='gravedad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='error',
            name='mensaje_usuario',
            field=models.CharField(blank=True, help_text='Mensaje amigable para el usuario', max_length=200),
        ),
        migrations.AddField(
            model_name='error',
            name='patron_detectado',
            field=models.CharField(blank=True, help_text='Patrón de error identificado', max_length=100),
        ),
        migrations.AddField(
            model_name='error',
            name='sugerencia_correccion',
            field=models.TextField(blank=True, help_text='Sugerencia de cómo corregir el error'),
        ),
        migrations.AddField(
            model_name='error',
            name='tipo',
            field=models.CharField(choices=[('formato', 'Error de Formato'), ('validacion', 'Error de Validación'), ('duplicado', 'Dato Duplicado'), ('requerido', 'Campo Requerido'), ('logico', 'Error Lógico'), ('sistema', 'Error del Sistema')], default='validacion', max_length=20),
        ),
        migrations.AddField(
            model_name='insignia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insignia',
            name='color',
            field=models.CharField(default='#FFD700', help_text='Color hexadecimal', max_length=20),
        ),
        migrations.AddField(
            model_name='insignia',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insignia',
            name='dias_consecutivos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insignia',
            name='errores_maximos',
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AddField(
            model_name='insignia',
            name='experiencia_otorgada',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='insignia',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='insignia',
            name='icono',
            field=models.CharField(default='fas fa-star', help_text='Clase CSS del icono (FontAwesome)', max_length=50),
        ),
        migrations.AddField(
            model_name='insignia',
            name='nivel_requerido',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insignia',
            name='precision_minima',
            field=models.FloatField(default=0.0, help_text='Precisión mínima requerida (0-100)'),
        ),
        migrations.AddField(
            model_name='insignia',
            name='puntos_otorgados',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='insignia',
            name='registros_minimos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insignia',
            name='tipo',
            field=models.CharField(choices=[('logro', 'Logro'), ('habilidad', 'Habilidad'), ('dedicacion', 'Dedicación'), ('calidad', 'Calidad'), ('liderazgo', 'Liderazgo')], default='logro', max_length=20),
        ),
        migrations.AddField(
            model_name='metrica',
            name='alerta_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metrica',
            name='contexto',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional del contexto'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='periodo',
            field=models.CharField(choices=[('minuto', 'Por Minuto'), ('hora', 'Por Hora'), ('dia', 'Por Día'), ('semana', 'Por Semana'), ('mes', 'Por Mes')], default='hora', max_length=20),
        ),
        migrations.AddField(
            model_name='metrica',
            name='umbral_maximo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrica',
            name='umbral_minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='direccion',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registro',
            name='dni',
            field=models.CharField(default='', help_text='Documento Nacional de Identidad', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI debe tener 7 u 8 dígitos')]),
        ),
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='registro',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('corregido', 'Corregido')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fuente',
            field=models.CharField(choices=[('web', 'Interfaz Web'), ('api', 'API REST'), ('bulk', 'Carga Masiva'), ('mobile', 'Aplicación Móvil')], default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='nombres',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='puntuacion_calidad',
            field=models.FloatField(default=0.0, help_text='Puntuación de calidad (0-100)'),
        ),
        migrations.AddField(
            model_name='registro',
            name='revisiones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-\\(\\)]+$', 'Formato de teléfono inválido')]),
        ),
        migrations.AddField(
            model_name='registro',
            name='tiempo_procesamiento',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='ultima_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mejor_racha',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificaciones_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='precision_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos_totales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='racha_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='registros_totales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema_preferido',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='tipo',
            field=models.CharField(choices=[('registros_por_hora', 'Registros por Hora'), ('tiempo_promedio_registro', 'Tiempo Promedio por Registro'), ('registros_por_dia', 'Registros por Día'), ('errores_detectados', 'Errores Detectados'), ('tasa_error', 'Tasa de Error (%)'), ('precision_promedio', 'Precisión Promedio (%)'), ('puntuacion_calidad_promedio', 'Puntuación Calidad Promedio'), ('sesiones_activas', 'Sesiones Activas'), ('tiempo_sesion_promedio', 'Tiempo de Sesión Promedio'), ('insignias_obtenidas', 'Insignias Obtenidas'), ('uptime_sistema', 'Tiempo Activo del Sistema (%)'), ('respuesta_api_promedio', 'Tiempo Respuesta API (ms)'), ('uso_cpu', 'Uso de CPU (%)'), ('uso_memoria', 'Uso de Memoria (%)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro',
            name='datos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['registro'], name='core_error_registr_1a9265_idx'),
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['tipo'], name='core_error_tipo_d5c9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['corregido'], name='core_error_corregi_231505_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['usuario', 'tipo', 'fecha'], name='core_metric_usuario_c16e20_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['tipo', 'fecha'], name='core_metric_tipo_29791e_idx'),
        ),
        migrations.AddIndex(
            model_name='metrica',
            index=models.Index(fields=['periodo'], name='core_metric_periodo_03b41c_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['usuario', 'fecha'], name='core_regist_usuario_ab77b2_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['estado'], name='core_regist_estado_ac59c1_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['dni'], name='core_regist_dni_417702_idx'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
