# Generated by Django 5.2.5 on 2025-09-03 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionsistema_logauditoria_notificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='notificaciones_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tema_preferido',
        ),
        migrations.AddField(
            model_name='usuario',
            name='formato_fecha',
            field=models.CharField(default='DD/MM/YYYY', help_text='Formato de fecha preferido', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idioma_preferido',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', help_text='Idioma preferido de la interfaz', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_estadisticas',
            field=models.BooleanField(default=True, help_text='Mostrar estadísticas en el perfil público'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificaciones_push',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones push'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_publico',
            field=models.BooleanField(default=False, help_text='Si el perfil es visible para otros usuarios'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona_horaria',
            field=models.CharField(default='America/Argentina/Buenos_Aires', help_text='Zona horaria del usuario', max_length=50),
        ),
        migrations.CreateModel(
            name='ComentarioRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.comentarioregistro')),
                ('likes', models.ManyToManyField(blank=True, related_name='comentarios_liked', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.registro')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('empleado', 'Empleado'), ('contacto', 'Contacto'), ('personalizado', 'Personalizado')], default='personalizado', max_length=20)),
                ('campos_requeridos', models.JSONField(default=list, help_text='Lista de campos obligatorios')),
                ('campos_opcionales', models.JSONField(default=list, help_text='Lista de campos opcionales')),
                ('validaciones', models.JSONField(default=dict, help_text='Reglas de validación personalizadas')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('veces_usada', models.PositiveIntegerField(default=0)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Registro',
                'verbose_name_plural': 'Plantillas de Registro',
            },
        ),
        migrations.CreateModel(
            name='ReportePersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('barras', 'Gráfico de Barras'), ('lineas', 'Gráfico de Líneas'), ('circular', 'Gráfico Circular'), ('tabla', 'Tabla de Datos'), ('metricas', 'Métricas Clave')], default='tabla', max_length=20)),
                ('campos_seleccionados', models.JSONField(default=list, help_text='Campos a incluir en el reporte')),
                ('filtros', models.JSONField(default=dict, help_text='Filtros aplicados al reporte')),
                ('agrupamiento', models.JSONField(default=dict, help_text='Configuración de agrupamiento')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('publico', models.BooleanField(default=False, help_text='Si otros usuarios pueden ver este reporte')),
                ('veces_ejecutado', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Personalizado',
                'verbose_name_plural': 'Reportes Personalizados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SesionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('registros_creados', models.PositiveIntegerField(default=0)),
                ('errores_detectados', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_registro', models.DurationField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('dispositivo', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Trabajo',
                'verbose_name_plural': 'Sesiones de Trabajo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TareaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('revision', 'Revisión Periódica'), ('limpieza', 'Limpieza de Datos'), ('backup', 'Copia de Seguridad'), ('reporte', 'Generación de Reporte'), ('notificacion', 'Envío de Notificación')], default='revision', max_length=20)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizada', 'Personalizada')], default='diaria', max_length=20)),
                ('hora_ejecucion', models.TimeField(default='09:00:00')),
                ('dias_ejecucion', models.JSONField(default=list, help_text='Días de la semana para ejecutar')),
                ('activa', models.BooleanField(default=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros específicos de la tarea')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea Automática',
                'verbose_name_plural': 'Tareas Automáticas',
            },
        ),
    ]
