# Generated by Django 5.2.5 on 2025-09-03 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_notificaciones_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('api', 'API REST'), ('webhook', 'Webhook'), ('database', 'Base de Datos'), ('email', 'Correo Electrónico'), ('sms', 'SMS')], default='api', max_length=20)),
                ('url_endpoint', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('headers', models.JSONField(default=dict)),
                ('autenticacion', models.JSONField(default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('estado_sincronizacion', models.CharField(default='pendiente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integración Externa',
                'verbose_name_plural': 'Integraciones Externas',
            },
        ),
    ]
